### ISSUE TITLE
GUI Input 

### ISSUE THREAD

**Issue by delaneyheileman** [SNL-WaterPower/siweed#18]
Here is a screen shot of the current GUI. Please give your input! 
![Screen Shot 2020-07-20 at 1 40 26 PM](https://user-images.githubusercontent.com/4690630/87982211-aece9980-ca93-11ea-8f80-7b07f3083be9.png)

**Comment by nickross4444** [comment]
![image](https://user-images.githubusercontent.com/42656158/122457170-9ac53d80-cf6b-11eb-8427-a9042d1eed5e.png)

@ryancoe I've put the "move over/pop up" boxes in the top corner of the banners, does it look alright? Where should the text pop up? I'm if you have an idea for what you want written in them, that would be helpful, otherwise I can come up with something.

**Comment by ryancoe** [comment]
@nickross4444 I think this looks good. Please go ahead and draft some language. Maybe you can create a YAML file with these messages that someone else (e.g., me) can later come in and edit easily.

**Comment by nickross4444** [comment]
The GUI now matches the mockup almost exactly, closing this issue.
![image](https://user-images.githubusercontent.com/42656158/124840436-35e87c00-df48-11eb-8527-653a01f7763f.png)

**Comment by ryancoe** [comment]
thanks @nickross4444. In the future let's aim for more targeted issues (this one was a bit ambiguous).
