### ISSUE TITLE
WEC motor torque constant

### ISSUE THREAD

**Issue by nickross4444** [SNL-WaterPower/siweed#59]
- [x] Get model number from the motor
- [x] Add model # to diagram(#27)
- [x] Use maxon documented torque constant in arduino code
- [x] Verify torque constant with water tests

**Comment by nickross4444** [comment]
We've determined the test should be redone with a few changes:

- larger buoy
- minimize static friction
- check for bowing in the rack
- measure resting point from the top and bottom
- try to find how much torque it takes to overcome the static friction at different positions(slowly ramp the command)

**Comment by dforbush2** [comment]
Hi Nick

I agree on all points except the last. I actually think LARGER torque command steps will be needed, especially at the extremes of position to get decent motion. I think the ramps would be helpful in figuring out the size these torque steps need to be, but I prefer the series of static steps as a test procedure. 

Here's a plot detailing the reasons as to why. Motor torque here is calculated from device motion as a change in the hydrostatic torque resulting from the displacement. Note the assymmetry and apparent hysteresis near larger displacements. 

![image](https://user-images.githubusercontent.com/30122876/118879821-6a2bae80-b8ae-11eb-9cd9-07b1c4978076.png)



Best,
Dom

**Comment by nickross4444** [comment]
@dforbush2  Thanks, noted

**Comment by ryancoe** [comment]
Can you make a plot of motor torque vs. current (`plot(cur,tau)`)?

**Comment by dforbush2** [comment]
Yes. It shows a decent but sort of rough trend, but the suggested Kt = 0.022, is quite far from the nominal. Maybe a units or missing a gear ratio?

![image](https://user-images.githubusercontent.com/30122876/118883199-35b9f180-b8b2-11eb-9922-e425b12d3390.png)

**Comment by ryancoe** [comment]
Thanks @dforbush2! I agree there is probably a gear ratio, looks like this has not been addressed in #27? Maybe @nickross4444 can look at this tomorrow?

**Comment by nickross4444** [comment]
@gbacelli and I ended up doing the test with a sinusoid instead of steps, giving us these plots:
![image](https://user-images.githubusercontent.com/42656158/119576356-d4909300-bd75-11eb-821f-913cdb1e8bdc.png)
![image](https://user-images.githubusercontent.com/42656158/119576363-d8241a00-bd75-11eb-9ce8-a380c2754d7f.png)
With a kt of 1.2085. The factory constant is 0.0078. I'm not sure what's going on here, maybe an incorrect unit conversion. This is the table I used:
[Torque Steps calculated.xlsx](https://github.com/SNL-WaterPower/siweed/files/6542686/Torque.Steps.calculated.xlsx)
On the bright side the static friction does look a lot better with the new larger buoy.

**Comment by ryancoe** [comment]
Can someone post a photo of the WEC motor assembly?

**Comment by nickross4444** [comment]
This is the test with the larger buoy: 
[Torque constant test 5-21-21.zip](https://github.com/SNL-WaterPower/siweed/files/6549773/Torque.constant.test.5-21-21.zip)

**Comment by ryancoe** [comment]
@nickross4444  - Can you plot up these latest results in the same style that @dforbush2 used?

**Comment by nickross4444** [comment]
@ryancoe [The most recent graphs](https://github.com/SNL-WaterPower/siweed/issues/59#issuecomment-848311526) are those results.

**Comment by ryancoe** [comment]
Right, duh. Sorry.

**Comment by stespenc83** [comment]
> ![image](https://user-images.githubusercontent.com/30122876/118883199-35b9f180-b8b2-11eb-9922-e425b12d3390.png)

This graph looks correct for the motor/gear combination. The torque is ~0.02Nm at 0.6A. The gear ratio for the 110321 gear that we purchased in this motor gear combo is ~4.4 (57/13). Combining this info together I get 7.6 mNm/A, which is very close to the 7.8 mNm/A on the motor data sheet.


> ![image](https://user-images.githubusercontent.com/42656158/119576363-d8241a00-bd75-11eb-9ce8-a380c2754d7f.png)

I don't know what changed for this plot other than using a sinusoid instead of steps for the input, but the data is not even close to agreeing with the earlier data. Torque is more than an order of magnitude larger.

**Comment by stespenc83** [comment]
> [Torque Steps calculated.xlsx](https://github.com/SNL-WaterPower/siweed/files/6542686/Torque.Steps.calculated.xlsx)

This formula in that Excel file could be the culprit for that latter plot being off. 
Column E uses `=C2*PI()*(0.8^2)` to compute displaced volume in cubic meters. I don't think this buoy is 80cm in diameter.

**Comment by stespenc83** [comment]
> > I also verified that the motor assembly is too short to include a gear set, the thinnest compatible planetary gearset I could find was still 15mm long, and the motor assembly is several mm shorter than its maximum length as specified on the dimensioned drawings.

I checked the motor dimensions as well. I measured the motor length to be 24mm, which is the data sheet value for the motor without an attached gear head. So unless the gear was removed between the first dataset shown here and now, the dataset, which I called good, is indeed off by a significant factor.

**Comment by stespenc83** [comment]
> I don't think this buoy is 80cm in radius.

I should have measured the buoy while I was out at the RVR, but using a diameter of 5 inches, I get 7.6mNm/A as the torque constant for the second dataset. That diameter seems plausible, and the torque constant is very close to the datasheet value for the gearless motor. I'd say that using the wrong diameter is currently the biggest source of error.

**Comment by nickross4444** [comment]
That's my mistake, the radius should have been 0.08. Here are the adjusted figures:
![image](https://user-images.githubusercontent.com/42656158/120576347-da265280-c3df-11eb-9969-c8eaa6168eab.png)
The torque constant now comes out to 0.0121
Here is the updated table with the corrected value:
[Torque Steps calculated.xlsx](https://github.com/SNL-WaterPower/siweed/files/6588448/Torque.Steps.calculated.xlsx)


@stespenc83 Thank you for taking a look at this. The primary difference between the first and second sets of test data was the size of the buoy. Though with other various changes that were made, I think we should focus mainly on the second set with the larger buoy.

**Comment by ryancoe** [comment]
- [ ] Use calipers to measure buoy diameter
- [ ] Increase thermal time constant
- [ ] Increase max motor speed to 20,000
- [ ] Run tests with ~5s period and 20s period, confirm same results

**Comment by nickross4444** [comment]
New tests done with the suggested changes and these files: 
[new Tau tests.zip](https://github.com/SNL-WaterPower/siweed/files/6666438/new.Tau.tests.zip)

We measured buoy diameter at 120mm, and increased the thermal time constant from 0.9 to 1.2s. The max speed is about 13,000rpm, but at no point did we cross 500rpm

First test, 20s sine wave:
![image](https://user-images.githubusercontent.com/42656158/122310483-aa8e4480-cecd-11eb-82b3-6ae77638ad26.png)
Torque constant: 0.0065 Nm/A

Second test, larger 20s sine wave:
Here you can see the thermal constant acting, so results may be less accurate. 
![image](https://user-images.githubusercontent.com/42656158/122310993-78c9ad80-cece-11eb-97f5-16c15aa62822.png)
Torque constant: 0.0069 Nm/A

 Third test, 5s sine wave:
![image](https://user-images.githubusercontent.com/42656158/122311140-c514ed80-cece-11eb-81b4-1841dc03e2db.png)
Torque constant: 0.0069 Nm/A


We also verified the length matches the 283828 motor without a gearbox, which has a stated torque constant of 0.0078 Nm/A

We are finally in the right range, but a little less. This is to be partially expected due to friction. @gbacelli and @ryancoe is this ~14% error acceptable?

**Comment by ryancoe** [comment]
Yes, this looks right!

**Comment by stespenc83** [comment]
I think this is looking very good. There are still a few improvements that could be made.

The linear fits are being biased by the leverage points at the ends of the curves. This is the main way that friction is lowering the measured torque constant. If you were to remove any points past ~0.3A magnitude, the linear fits would have a higher slope. I did this, and got: 

![image](https://user-images.githubusercontent.com/33231333/122455510-b4fe1c00-cf69-11eb-9315-1f60ce4345fd.png)
6.53 mNm/A ==> 7.57 mNm/A

![image](https://user-images.githubusercontent.com/33231333/122455802-09a19700-cf6a-11eb-8331-ad3bd092cb97.png)
6.90 mNm/A ==> 7.41 mNm/A

![image](https://user-images.githubusercontent.com/33231333/122455953-335abe00-cf6a-11eb-806e-e14a16a0d51b.png)
6.92 mNm/A ==> 7.57 mNm/A


Regarding my comment about friction: Since torque is being estimated from displacement and the frequency is low (inertial and viscous effects are small), the friction shows up as a "constant" offset from the ideal torque constant and doesn't affect the slope.

![image](https://user-images.githubusercontent.com/33231333/122457626-13c49500-cf6c-11eb-9e10-591f239741e4.png)
So here I show the difference between the actual and predicted torque (torque error) based on the two fits. With the original fit, there is a clear trend in the middle of the data with an upward slope. With the fit that removes the leverage points, the error is more flat (more easily seen on the bottom section). The average offsets are similar in magnitude (0.44 and 0.46 mNm) on either side of zero error, as expected. So the friction is ~0.45mNm.

With the new measured torque constant averaging 7.52 mNm/A, we're measuring within 4% of the datasheet value. Which I'd say is quite good. You can probably close this issue.

**Comment by nickross4444** [comment]
@stespenc83, very nice, thank you, I will use 7.52 mNm/A as our constant.

**Comment by ryancoe** [comment]
@nickross4444 - Please incorporate this material in the HardwareX paper. We should discuss/present

- Equation for torque constant
- How we infer the torque applied based on the vertical displacement of the WEC and hydrostatics (with equations)
- Work added by @stespenc83 to deal with the friction/hysteresis (with plots)
